### ISSUE TITLE
那如何将一个旧的应用打包成一个webcomponent在新系统中引入呢？

### ISSUE THREAD

**Issue by Create-Peace** [phodal/micro-frontend#1]

**Comment by phodal** [comment]
要引入旧的系统，就需要将旧的应用以 Web Components 的形式构建出来。

而具体能不能将应用构建成 Web Components，要看框架本身能不能支持？如果不能，让就需要我们提供相应的支持机制。

一种简单的试验方式是，先从 ``HTML Imports`` 开始：``<link rel="import" href="myfile.html">`` 再具体去解决 import 的过程中遇到哪些问题。
