### ISSUE TITLE
问个偏业务点的问题，关于鉴权

### ISSUE THREAD

**Issue by bigbigbo** [phodal/micro-frontend#10]
假设我已经拆解成多个子应用并且能实现独立部署独立运行，也可以将这些子应用聚合在一起作为一个聚合应用发布。
在这样的场景下，如果各个子应用都需要登录权限，该如何去设计能实现子应用和聚合应用使之运行良好呢？

**Comment by phodal** [comment]
鉴权要么是用 token 要么是用 cookie，聚合发布的时候，他们都是同域，不存在这样的问题。只需要在基座应用里，实现登录功能即可。

**Comment by bigbigbo** [comment]
那如果我子应用独立部署，也想能登陆怎么处理比较好（如果跳转到聚合应用里登陆并且部署在不同域的情况下会有问题）？是把登陆这块也拎出来作为一个子应用而不是基座应用里实现，然后想要独立部署子应用，那就连带着把登陆也部署了，就是至少部署1个子应用和1个登陆应用。

**Comment by phodal** [comment]
可以，哈哈

**Comment by bigbigbo** [comment]
谢谢回答。今天你的书就要到手了，到时在拜读下:smiley:
