### ISSUE TITLE
不使用 iframe 时只能使用协商缓存？

### ISSUE THREAD

**Issue by mantou132** [phodal/micro-frontend#11]
子项目部署之后是一个 url，宿主项目通过这个 url 来加载他。

不像 iframe ，是无缓存加载的 html 文档，可以在 html 中引用新版资源

如果更新子项目时还要更新宿主环境，那就不叫独立部署了。

**Comment by phodal** [comment]
我不是很懂你的问题。

你说的这些缓存应该都是 HTTP 缓存，是由 HTTP 服务器控制的和应用没有关系。

**Comment by mantou132** [comment]
举个例子：
独立部署，宿主 app 加载子应用是使用的 `{src: 'a.b.c/a.js'}`
那么不更新宿主 app 时这个 url 永远不会变。

子应用要更新，最终打包部署，最新资源还是 'a.b.c/a.js'，那么怎么更新呢？

只能使用协商缓存，宿主 app 加载子应用时必须问服务端有没有新资源。

而我们现在加载静态资源最佳实践确实 cdn + 强制缓存，构建时加上 hash 或者版本号。

**Comment by phodal** [comment]
静态资源肯定要 hash…….。不 hash，所有的缓存都会出现问题。

所以，我觉得是你们设计有问题啊，你要加载子应用，肯定存在某个配置。这个配置说明应用在哪里。
