### ISSUE TITLE
conceptions question

### ISSUE THREAD

**Issue by ghost** [phodal/micro-frontend#13]
Hi!
Early I was try to write to you email about consultation and now, as you ask, will write here. Frst of all, thank you for your [post](https://dev.to/phodal/micro-frontend-architecture-in-action-4n60) again. It's great and better of all i read about this theme.
My question is not about some framework or library but I want know common principles and get some practice help for newbe. 
Have next situation:
I have three web-apps. 
1. All use spa practises at front. Uses handmade framework with partial of knockoutjs and requirejs for all and share css. 
2. Base initialisation is MVC on java.

Separetly all is fine, but I want make some common shell for loading apps in one ui witout page reloding. Its must looks like additional menu where user can switch apps and then work with app in content area.

I have next targets:
1. All apps must be availible as through common shell so as separated.
2. Planed use different tecnologies and practics on new apps like Vue, Angular for ui.
3. Each app developing by own team.
Actualy, all targets in foreword of you post)
In case I think use first method from your post - Basic: Application Distribution Routing. 
So, if you cane give som practice advices or examples, or show best way, its will be wonderful.

Thanks a lot!

**Comment by phodal** [comment]
Hello,

As we know, [single-spa](https://github.com/CanopyTax/single-spa) is a good example to show how to use different frameworks in same page. You can get some ideas for it.

And, if you try to use new framework, you can try Web Component tech with new frameworks, like Stencil.js with Angular, pure Angular in Web Components or others.

**Comment by ghost** [comment]
Thanks a lot!

**Comment by ghost** [comment]
One more.
Thanks again for your recommendations! 
But I suppose don't give enough info about my problem. My fail. 
In real my questions was more about backend functions. Single-spa looks like all 'apps' or parts still hosted in same project and deploed on one host. Separation is more logical. Looks like all teams work in one project and dont touch folders of other teams. 
In my case all apps are diferent projects hosted on diferent servers. Can be some will be writing on pyton, some on java or .net as base lang. Seems, in my case, managin aps in browser is not big deal cause in one time user work with only one app.  
The problem for me is - how can I get entry point for app form server through 'shell app'?  At now all apps have index controller, then on index page shoot loading of requre.js --> main.js --> app.js. app.js managin all other libs as spa-lib, binding, routing, events, components, etc. Herewith, base url is consant cause request goes to one server. 
Shell app neded for managing switching beetwen apps. When its hapening base url for pages and js request changing. 
I try use sequence: browser request with requered app params --> Shell app host --> geting jsp from app host via rest --> return to browser result. I have fail. And I undestand - that wrong idea. But I cant find right way. Maybe You can help me? 
Thanks again!

**Comment by phodal** [comment]
Sorry, I try to figure out what is your pain, but failure.

Have you draw some a simple architecture digram  of system ? I think a visual architecture will help  use to understand it.

**Comment by ghost** [comment]
Thank! Just a moment.

**Comment by ghost** [comment]
![now](https://user-images.githubusercontent.com/46805365/66567913-0d242e80-eb8a-11e9-9ce3-42455a1cfd0e.png)
![target](https://user-images.githubusercontent.com/46805365/66567924-12817900-eb8a-11e9-8229-e1d37a64b94d.png)

**Comment by phodal** [comment]
In my understand, the architecture is works. And Is you problem is how to build Shell App ? 

The Shell App can load/store servers or frontend application information, then we can manage it.

**Comment by ghost** [comment]
Exactly. Separately all apps works fine. And they must goes available in both cases - as separate app so as part of shell. Sorry,  I was in a hurry. Сonnecting lines on target schem represent a schematic meaning

**Comment by phodal** [comment]
in this scene, you can try in two different ways:

1. software engineering. such as build a library to share in shell apps, use git submodule to share them.
2. technology integration. build a simple framework base on single-spa

**Comment by ghost** [comment]
Thanks! Second way looks more interested. With user-side of sell all understandable and its less problem. Can you show some way for server-side? Clarification of the issue: Does exist any way to use same mvc controller on app server-side when user get access through Shell app?

**Comment by phodal** [comment]
it sounds like BFF (backend for frontend) will have same MVC controller. But it depends on your business.

**Comment by ghost** [comment]
Thansk a lot! I will close issue.
