### ISSUE TITLE
routing between micro front ends

### ISSUE THREAD

**Issue by sakshigarg9** [phodal/micro-frontend#15]
Hi phodal,
For routing between micro front-ends, where my micro-front ends are separate Angular solutions, how do I go about it? Can you share some reference links/articles relating to explanations using Angular?

For Eg. a scenario where on the click of a button in micro front-end(1) I need to render a web component within micro front-end(2) and also change the url of the page.

Thanks in advance!

**Comment by phodal** [comment]
Window Events or other Pub/Sub pattern code
