### ISSUE TITLE
Load config via app.json

### ISSUE THREAD

**Issue by iyeldinov** [phodal/micro-frontend#16]
Hi, can you give more detailed explanation about deployment.
How is your CI/CD built? 

For example
Team A updated their micro app and pushed code to team repo. What will happen next?
CD pipeline triggered and bundles are created. Where do these files are uploaded? Are they in separate docker container?

**Comment by phodal** [comment]
Sorry, guys, it too many root PR in my GitHub.

For the CI/CD, just use Jenkins will be enough, don't need some changes if you use [Mooa](https://github.com/phodal/mooa) why. Every repo is separete that is microfrontends' way
