### ISSUE TITLE
代码隔离要怎么做呢？

### ISSUE THREAD

**Issue by lili21** [phodal/micro-frontend#22]
比如js的隔离（避免变量污染，全局变量被改）
css的隔离

**Comment by phodal** [comment]
js 隔离靠沙箱
css 主要靠规范

**Comment by lili21** [comment]
沙箱有什么好的做法吗？需要考虑到哪些方面？

用Proxy做？

**Comment by lili21** [comment]
不考虑兼容性的话，我能想到的是用Proxy去做，

with (proxy) {
  // 运行子应用
}

**Comment by phodal** [comment]
看这个吧，很成熟了 https://github.com/umijs/qiankun/blob/master/src/sandbox/proxySandbox.ts

**Comment by lili21** [comment]
看了下，还是用eval做的。我的想法是基于webpack5的module federation去实现
