### ISSUE TITLE
我买了你的书，你却告诉我它开源， 悲伤2021

### ISSUE THREAD

**Issue by tiezhusu** [phodal/micro-frontend#23]
### /(ㄒoㄒ)/~~

**Comment by phodal** [comment]
哈哈，虽是如此，但是书上写得比较详细，比较系统。

顺便一说：这就是我的模式，我的三本书都是这样的。先写文章，然后整合开源，伸手党直接 GitHub 啊，有情怀的支持一下作者的劳动。
