### ISSUE TITLE
请教：postMessage 事件对于应用的侵入性太强怎么理解

### ISSUE THREAD

**Issue by nuonuoge** [phodal/micro-frontend#4]

**Comment by phodal** [comment]
``postMessage`` 的应用侵入性太强是指？

**Comment by nuonuoge** [comment]
文章中这段：
通讯机制。直接在每个应用中创建 postMessage 事件并监听，并不是一个友好的事情。其本身对于应用的侵入性太强，因此通过 iframeEl.contentWindow 去获取 iFrame 元素的 Window 对象是一个更简化的做法。随后，就需要定义一套通讯规范：事件名采用什么格式、什么时候开始监听事件等等。

**Comment by phodal** [comment]
就是需要修改相关的事件代码而已

**Comment by nuonuoge** [comment]
在mooa框架里面获取子的window对象，然后在mooa框架统一为子window添加事件方法，而不是去每个子应用里面写，非侵入是指这样吗

**Comment by phodal** [comment]
是的。相当于提供一个公共的 pub-sub

**Comment by nuonuoge** [comment]
好滴，感谢解答
