### ISSUE TITLE
关于子项目打包

### ISSUE THREAD

**Issue by zhangdexian** [phodal/micro-frontend#5]
您好，每一个子项目是独立打包部署的吗？我现在用了一个single-spa的框架，现在可以将不同框架的项目都集成起来，但是需要把所有的项目放在一个项目里集中打包。请问有什么好的解决方案吗

**Comment by phodal** [comment]
Hello，我编写的 [Mooa](https://github.com/phodal/mooa) 框架是每个项目独立部署的。

建议的解决方案是在 Mooa 的基础上，改出你们需要的版本。 

Mooa 使用的是 Angular 框架的，这里有一个 React 相关的实现原理：https://github.com/phodal/mooa/issues/19

**Comment by zhangdexian** [comment]
现在所有项目的技术栈主要是Vue,就是想不明白怎么将打包后的项目文件集成到single-spa或者Mooa中，恳求指点，感激不尽~

**Comment by phodal** [comment]
Mooa 只支持 Angular，Single-SPA 不支持独立构建。。。你们需要自己修改一下
