### ISSUE TITLE
请问我这个项目算不算微前端？

### ISSUE THREAD

**Issue by mqhe2007** [phodal/micro-frontend#6]
https://github.com/mqhe2007/admincraft

Admincraft 是一个基于Vue并且支持模块化分布部署和加载的admin快速开发工具。

**Comment by phodal** [comment]
可以看一下定义：

> 微前端是一种类似于微服务的架构，它将微服务的理念应用于浏览器端，即将 Web 应用由单一的单体应用转变为多个小型前端应用聚合为一的应用。各个前端应用还可以独立运行、独立开发、独立部署。

然后，你看看你这个框架，能否让每个应用独立运行、独立开发和独立部署。

**Comment by mqhe2007** [comment]
模块的独立开发和独立部署没问题。

独立运行的话取决于cli构建目标，如果构建为包含admincraft的话，独立部署就可以独立运行；如果构建时不包含admincraft，则必须载入包含admincraft的其他模块才能运行。

换言之，admincraft内部集成的各种库形成了一个模块运行环境。

个人觉得算是一种具体的微前端实现吧。

**Comment by phodal** [comment]
如果独立开发、运行和部署没有问题的话，你这也算是微前端实现了~。
