### ISSUE TITLE
如何分开上报错误？

### ISSUE THREAD

**Issue by mantou132** [phodal/micro-frontend#8]
不使用 iframe 的情况；

公共组件和一个页面不是同一个团队开发的，需要将两者的发生的错误堆栈上报到不同的团队。

好像只能从 stack 中的 path 来区分了啊？

**Comment by phodal** [comment]
为什么不将提供一个上报错误的软件包（npm包），然后共同使用呢？

**Comment by mantou132** [comment]
处理错误也是分开工作的呀
确切的说就是我的页面发生的错误报告给我，别人的组件的错误不要报告给我。

**Comment by phodal** [comment]
哈哈，你们的错法好特别，不符合一般习惯。微前端实施起来，就是一个完整的系统。怎么能分开错误？
